---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  dev = "svg"
)
```

# ggifau

<!-- badges: start -->
<!-- badges: end -->

The goal of ggifau is to ...

## Installation

You can install the development version of ggifau like so:

``` r
# install.package("devtools")
devtools::install_github("adrianadermon/ggifau")
```

## Example

This is a basic example which shows you how to solve a common problem:

Load the package:
```{r load-package}
library(ggifau)
```

```{r example-theme}
ggplot(mtcars, aes(x = disp, y = mpg, color = factor(carb), shape = factor(carb))) +
  geom_point() +
  theme_ifau()
```

```{r example-shapes}
ggplot(mtcars, aes(x = disp, y = mpg, color = factor(carb), shape = factor(carb))) +
  geom_point() +
  scale_colour_ifau() +
  scale_shape_ifau() +
  theme_ifau()
```

```{r example-lines}
ggplot(mtcars, aes(x = disp, y = mpg, color = factor(carb), linetype = factor(carb))) +
  geom_line() +
  scale_colour_ifau() +
  scale_linetype_ifau() +
  theme_ifau()
```

```{r example-bar}
ggplot(mtcars, aes(x = gear, y = mpg, fill = factor(carb))) +
  geom_col(position = position_dodge()) +
  scale_fill_ifau() +
  theme_ifau()
```

```{r example-hist}
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram() +
  theme_ifau()
```


The `ggifau()` function sets the default theme, default colors, and updates some aesthetics.
```{r example-all}
ggifau()

ggplot(mtcars, aes(x = disp, y = mpg, color = factor(carb), shape = factor(carb))) +
  geom_point()
```

```{r example-hist2}
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram()
```
